### ISSUE TITLE
Division should allow numerical values for the divisor

### ISSUE THREAD

**Issue by Wildhoney** [jonathantneal/css-typed-om#3]
For example, in the official spec, dividing the dividend `x` by the divisor `y` where `y` is `Number` yields a `CSSUnitValue` &ndash; when you pass an object as the divisor (such as `CSS.px`), the official spec yields a `CSSMathProduct`.

However in the case of this polyfill, if the divisor is a `Number` then you simply yield `null` which doesn't seem to conform to how the implementation should be.

```javascript
CSS.px(10).div(2); // CSSUnitValue {value: 5, unit: "px"} (official)
CSS.px(10).div(2); // null (polyfill)
```

I would fix it myself with a PR, but I'm not entirely sure the best way to fix up the [`div` method](https://github.com/jonathantneal/css-typed-om/blob/master/lib/CSSNumericValue.js#L36-L56). Whether you have a preference for one way over another 👍

**Comment by jonathantneal** [comment]
This has been implemented in 0.4.0!
