### ISSUE TITLE
What's the performance like?

### ISSUE THREAD

**Issue by matthew-dean** [jonathantneal/css-typed-om#4]
Glad to see someone is doing this. Have you done any performance testing to see what the fastest path of style updates is in the browser? That kind of data is really hard to find.

**Comment by jonathantneal** [comment]
No. How would you recommend I test it? I used to browserscope, but found it unresponsive too often. If you can give me any pointers, I’d be happy to run tests.

**Comment by matthew-dean** [comment]
@jonathantneal Yeah, honestly, I have no idea. I've never seen research into whether browsers do better with, say, updating a style tag with new `innerHTML` vs creating / replacing a style tag (for browsers that don't support typed OM.

But I guess this is more about polyfilling Typed OM on elements themselves, vs reading / writing typed styles from a stylesheet. Correct?

**Comment by jonathantneal** [comment]
That’s correct. I think we can close this issue. 😄
